package MyAI;

import java.util.ArrayList;
import java.util.Collections;

public class HiddenNode extends Node {
    ArrayList<Double> weights;
    ArrayList<Node> inputs;
    private Double output;
    private Boolean hasChanged;
    Double bias;
    @Override
    public Double getOutput() {
        if (hasChanged) {
            Double out = 0.0;
            for (int i = 0; i < inputs.size(); i++)
                out += inputs.get(i).getOutput() * weights.get(i);
            return out/inputs.size() + bias;
        } else
            return output;
    }


    // constructors and stuff are below, mostly the autogenerated stuff

    HiddenNode(ArrayList<Node> inputs, ArrayList<Double> weights, Double bias) {
        this.inputs = inputs;
        this.bias = bias;
        this.weights = weights;
        this.hasChanged = true;
        this.output = 0.0;
    }
    HiddenNode(ArrayList<Node> inputs) {
        this(inputs, new ArrayList<>(inputs.size()), 0.0);
        for (int i = 0; i < inputs.size(); i++) {
            this.weights.add(1.0);
        }
    }

    public ArrayList<Double> getWeights() {
        return weights;
    }

    public void setWeights(ArrayList<Double> weights) {
        this.weights = weights;
        hasChanged = true;
    }
    public void setWeight(int index, Double value) {
        this.weights.set(index,value);
        hasChanged = true;
    }

    public ArrayList<Node> getInputs() {
        return inputs;
    }

    public void setInputs(ArrayList<Node> inputs) {
        this.inputs = inputs;
        hasChanged = true;
    }

    public Double getBias() {
        return bias;
    }

    @Override
    public String toString() {
        return "HiddenNode{" +
                "weights=" + weights +
                ", bias=" + bias +
                '}';
    }

    public void setBias(Double bias) {
        this.bias = bias;
        hasChanged = true;
    }

}
